### ISSUE TITLE
exit codes are not propagated

### ISSUE THREAD

**Issue by rgommers** [pydoit/pydevtool#1]
xref https://github.com/scipy/scipy/issues/16476; it seems to be the case `@cli.command` and `@cli.cls_cmd` that exit codes are not propagated. I tried returning True, False or a non-zero integer from the `authors` command in SciPy's `dev.py`, and the result of `$ echo $?` afterwards remains `0`.

[click.testing.Result.exit_code](https://click.palletsprojects.com/en/8.1.x/api/#click.testing.Result.exit_code) does hold the exit code we need it looks like, and we want the decorators to forward that result.

**Comment by schettino72** [comment]
It seems click design is that you need to explicitly call `sys.exit()`
https://github.com/pallets/click/issues/747

**Comment by rgommers** [comment]
Ah great, thanks for finding that!
